# Site settings
title: Roman12663 - Content Creator # Name of browser tab
tagline: Exciting Gaming Streams and Videos # Short description that will appear next to the title of the browser tab
description: Join Roman12663 for exciting Twitch streams and YouTube videos. Experience thrilling gaming adventures and engage with a vibrant community. Subscribe now! # Short description of your site that will appear in search engines
url: 'https://roman12663.github.io'

# Build settings
client:
  intro: Hey, I'm # Hello, I'm { name }!
  name: Roman # John Doe | Jane D.
  profession: Content Creator # Doer of things
  portrait_url: # Leave blank to use local portrait in assets/

social:
  - platform: Twitch
    handle: roman12663
  - platform: YouTube
    handle: '@roman1266'
  - platform: Instagram
    handle: roman12663
  - platform: TikTok
    handle: '@roman12663'

# TODO: Add to gem
about_me:
  img: # The image to be used for this section. Leave blank to use local portrait in assets/
  bio: # Who are you? Explain in third person! e.g.) "Person is a human being who lives in planet Earth. They drink water, breathe air, and eat food."
    Roman, also known as Roman12663 or Roman1266, is a content creator who should add more info about themselves here!

theme: jam-flow
colors:
  preset:
    # 1 = Elegant Lavender
    # 2 = Candy Crush
    # 3 = Cotton Candy
    # 4 = Coral Reef
  use_custom: # Toggle colors defined below this
  primary:
  secondary:
  tertiary:
  accent:
  accent_alt:
  text:

collections:
  articles:
    output: false
  redirect:
    output: true
    permalink: /:path

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
